version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: asset-management-db
    environment:
      POSTGRES_DB: AssetManagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/AssetManagementAPI/Seeds/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - asset-management-network

  # Backend API
  backend:
    build:
      context: ./backend/AssetManagementAPI
      dockerfile: Dockerfile
    container_name: asset-management-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AssetManagement;Username=postgres;Password=postgres
      - JwtSettings__Secret=your-super-secret-key-here
      - JwtSettings__Issuer=AssetManagement
      - JwtSettings__Audience=AssetManagementUsers
      - JwtSettings__ExpirationHours=24
    ports:
      - "5124:5124"
    depends_on:
      - postgres
    networks:
      - asset-management-network
    volumes:
      - ./backend/AssetManagementAPI:/app
      - /app/bin
      - /app/obj

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asset-management-frontend
    environment:
      - VITE_API_URL=http://localhost:5124
      - VITE_APP_NAME=Asset Management System
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - asset-management-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Redis (for caching, optional)
  redis:
    image: redis:7-alpine
    container_name: asset-management-redis
    ports:
      - "6379:6379"
    networks:
      - asset-management-network
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  asset-management-network:
    driver: bridge
